name: 💅 Feature Request
description: Submit a detailed feature request with a concrete proposal, including an exhaustive API / UI design
labels: feature
body:
  - type: markdown
    attributes:
      value: |
        Important things:

        - We expect you to submit a feature request including a real design (API / UI...), not just a basic idea.
        - The design does not have to be perfect, we'll discuss it and fix it if needed.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: API design
      description: |
        Please describe how Readout users will enable and configure this feature, and what it will look like.

        Please explain in an exhaustive way what are the config/plugin options and their respective effects. For visual elements, please send us some screenshots/mockups of what it should look like. You can use https://excalidraw.com to create simple mockups.

  - type: textarea
    attributes:
      label: Have you tried building it?
      description: |
        Please explain how you tried to build the feature by yourself, and how successful it was.

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you do check this box, please send a pull request within 7 days after a maintainer's approval so we can still delegate this to someone else.

        Note that for feature issues, we still require you to fully fill out this form and reach consensus with the maintainers on API design before rushing to implement it, so that you don't waste your time.
      options:
        - label: I'd be willing to contribute this feature to Readout myself.
